baseURL: "https://MParnin.github.io/"
languageCode: en-us
title: MP
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - identifier: About
      name: About
      url: /about/
      weight: 10
    - identifier: CTF Write-ups
      name: CTF Write-ups
      url: /write-ups/
      weight: 20
    - identifier: Projects
      name: Projects
      url: /projects/
      weight: 30
    #- identifier: Malware Analysis
      #name: Malware Analysis
      #url: /malwareanalysis/
      #weight: 20
    #- identifier: Smart Contract Auditing
      #name: Smart Contract Auditing
      #url: /smartcontracts/
      #weight: 30  
    - identifier: Conferences
      name: Conferences
      url: /conferences/
      weight: 50
    - identifier: Posts
      name: Posts
      url: /posts/
      weight: 60
    - idenfitifer: Search
      name: Search
      url: /search
      weight: 80
    #- identifier: Archives
      #name: Archives
      #url: archives
      #weight: 90
    #- identifier: Gitbook
      #name: Gitbook
      #url: https://example.org
      #weight: 80

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ExampleSite
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: MP
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "MP"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Mike Parnin
    #subtitle: "Stuff about me."
    imageUrl: "/home/luna.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: 
    buttons:
      - name: Contact Me
        url: "mailto:MParnin@protonmail.com"
      #- name: Tags
        #url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: hackthebox
      url: "https://app.hackthebox.com/profile/1197928"
    - name: TryHackMe
      url: "https://tryhackme.com/p/0xMP"
    - name: github
      url: "https://github.com/MParnin"
    - name: linkedin
      url: "https://www.linkedin.com/in/mikeparnin/"
    - name: twitter
      url: "https://twitter.com/0xMikeP"
    #- name: email
    #  url: "mailto:zeroxmp@protonmail.com"


  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.1
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    #noClasses: false
    #anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai